[package]
name = "portal_still_alive"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
opt-level = "z"
strip = true
panic = "abort"
codegen-units = 1

[dependencies]
anyhow = "1.0.98"
ctrlc = "3.4.7"
regex-lite = "0.1.6"
term_size = "0.3.2"
